/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb -T 
Files: laptop.glb [978KB] > C:\dev\portfolio\public\models\laptop-transformed.glb [77.76KB] (92%)
Author: senthil123 (https://sketchfab.com/senthil123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-426afac17c664f1a9e3224394024fb7e
Title: Laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadows receiveShadows geometry={nodes.Laptop_Laptop1_0.geometry} material={materials.Laptop1} scale={0.016} />
    </group>
  )
}

useGLTF.preload('/models/laptop-transformed.glb')
